on:
  pull_request:
name: auto-release
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3.0.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        debug: true
        script: |
          // only approve PRs from release-please[bot]
          if (context.payload.pull_request.user.login !== "release-please[bot]") {
            return;
          }

          // only approve PRs like "chore: release <release version>"
          if ( !context.payload.pull_request.title.startsWith("chore: release") ) {
            return;
          }

          // trigger auto-release when
          // 1) there are dependency updates only
          // 2) there are no open dependency update PRs in this repo (to avoid multiple releases)
          if (
            context.payload.pull_request.body.includes("Fix") ||
            context.payload.pull_request.body.includes("Build") ||
            context.payload.pull_request.body.includes("BREAKING CHANGES") ||
            context.payload.pull_request.body.includes("Features")
          ) {
            console.log( "Not autoreleasing since it is not a dependency-update-only release. " );
            return;
          }

          // list all open pull requests
          const promise = github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open'
          });
          const open_pulls = await github.paginate(promise)
          console.log("paginated pulls: " + JSON. stringify(open_pulls));
          return;


          // approve release PR
          await github.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Rubber stamped release!',
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE'
          });

          // attach kokoro:force-run and automerge labels
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['kokoro:force-run', 'automerge']
          });