on:
  pull_request:
name: auto-release
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3.0.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          // approve release PR
          await github.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Rubber stamped release!',
            pull_number: context.payload.pull_request.number,
            event: 'APPROVE'
          });

          // attach kokoro:force-run and automerge labels
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: ['kokoro:force-run', 'automerge']
          });